name: rickrack
version: 2.8.42
summary: Generate harmonious colors freely.
description: |
    Rickrack is a free and open-source color palette generator. It provides various functionalities to generate a harmonious set of colors, offering you better color combination options. You can easily obtain the desired color combinations through color wheel selection, color picking from images, and more. It offers support for various color palette formats like aco, ase, gpl, and xml, making them easily importable into popular image processing software such as Photoshop, Clip Studio Paint, GIMP, Krita, and Inkscape. You can apply these colors to your own creations or share them with others.

grade: stable
base: core20
confinement: strict

parts:
    rickrack:
        plugin: dump
        source: https://github.com/eigenmiao/Rickrack/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Rickrack_v$SNAPCRAFT_PROJECT_VERSION_en_linux_x86_64.tar.gz
        override-stage: |
            snapcraftctl stage
            echo "{\"store_loc\": false}" > $SNAPCRAFT_STAGE/settings.json
        stage-packages:
            - libFcitx5Qt5DBusAddons.so.1
            - libFcitxQt5DBusAddons.so.1
            - libGL.so.1
            - libQt53DAnimation.so.5
            - libQt53DCore.so.5
            - libQt53DInput.so.5
            - libQt53DLogic.so.5
            - libQt53DQuick.so.5
            - libQt53DQuickScene2D.so.5
            - libQt53DRender.so.5
            - libQt5EglFSDeviceIntegration.so.5
            - libQt5EglFsKmsSupport.so.5
            - libQt5Gamepad.so.5
            - libQt5MultimediaQuick.so.5
            - libasound.so.2
            - libdrm.so.2
            - libgtk-3.so.0
            - libodbc.so.2
            - libpq.so.5
            - libpulse-mainloop-glib.so.0
            - libpulse.so.0
            - libtinfo.so.5
            - libxcb-dri2.so.0
            - libxcb-dri3.so.0
            - libxcb-xinerama.so.0
            - libxcb.so.1

slots:
  dbus-rickrack:
    interface: dbus
    bus: session
    name: com.eigenmiao.rickrack

apps:
    rickrack:
        environment:
            LD_LIBRARY_PATH: $SNAP:$LD_LIBRARY_PATH
            PATH: $SNAP:$PATH
            QML2_IMPORT_PATH: $SNAP/PyQt5/Qt/qml:$QML2_IMPORT_PATH
            QT_PLUGIN_PATH: $SNAP/PyQt5/Qt/plugins:$QT_PLUGIN_PATH
            QT_LINUX_ACCESSIBILITY_ALWAYS_ON: 1
            QT_QPA_PLATFORMTHEME: appmenu-qt5
            QT_ACCESSIBILITY: 1
            QT_IM_MODULE: fcitx
        command: Rickrack
        plugs:
            - desktop
            - framebuffer
            - camera
            - network
            - home
            - opengl
            - x11
            - desktop-legacy
        slots:
            - dbus-rickrack
